#!/bin/bash

# Functional Point Analysis Runner
# For Mangrove Visualization System
# Author: AI Assistant
# Date: March 30, 2026

PROJECT_DIR="/home/nlplab/Prabu/mangroveviz"
REPORT_DIR="$PROJECT_DIR/reports"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

echo "=========================================="
echo "Functional Point Analysis Runner"
echo "Project: Mangrove Visualization System"
echo "Date: $(date)"
echo "=========================================="

# Create reports directory
mkdir -p "$REPORT_DIR"

# Check if PHP tools are available
if command -v php &> /dev/null; then
    echo "✓ PHP is available"

    # Check PHPLoc
    if [ -f "$PROJECT_DIR/phploc.phar" ]; then
        echo "✓ PHPLoc found, running analysis..."
        php "$PROJECT_DIR/phploc.phar" --log-json="$REPORT_DIR/phploc_$TIMESTAMP.json" "$PROJECT_DIR/web"
        echo "✓ PHPLoc analysis completed: $REPORT_DIR/phploc_$TIMESTAMP.json"
    else
        echo "✗ PHPLoc not found, skipping..."
    fi

    # Check PHPMetric
    if [ -f "$PROJECT_DIR/phpmetrics.phar" ]; then
        echo "✓ PHPMetric found, running analysis..."
        php "$PROJECT_DIR/phpmetrics.phar" --report-html="$REPORT_DIR/metrics_$TIMESTAMP" "$PROJECT_DIR/web"
        echo "✓ PHPMetric analysis completed: $REPORT_DIR/metrics_$TIMESTAMP/"
    else
        echo "✗ PHPMetric not found, skipping..."
    fi
else
    echo "✗ PHP not available, using Python analysis instead..."
fi

# Python code analysis as alternative
echo "Running Python code analysis..."
python3 -c "
import os
import glob
from pathlib import Path

project_dir = '$PROJECT_DIR'
web_dir = os.path.join(project_dir, 'web')

# Count Python files and lines
py_files = glob.glob(os.path.join(web_dir, '**', '*.py'), recursive=True)
total_lines = 0
total_files = len(py_files)

for file in py_files:
    try:
        with open(file, 'r', encoding='utf-8') as f:
            lines = len(f.readlines())
            total_lines += lines
    except:
        pass

# Count classes and functions
total_classes = 0
total_functions = 0

for file in py_files:
    try:
        with open(file, 'r', encoding='utf-8') as f:
            content = f.read()
            total_classes += content.count('class ')
            total_functions += content.count('def ')
    except:
        pass

print(f'Python Files: {total_files}')
print(f'Total Lines: {total_lines}')
print(f'Classes: {total_classes}')
print(f'Functions: {total_functions}')
print(f'Average LOC per file: {total_lines/total_files:.1f}' if total_files > 0 else 'N/A')
" > "$REPORT_DIR/python_analysis_$TIMESTAMP.txt"

echo "✓ Python analysis completed: $REPORT_DIR/python_analysis_$TIMESTAMP.txt"

# Generate summary report
cat > "$REPORT_DIR/summary_$TIMESTAMP.md" << EOF
# Functional Point Analysis Summary
## Mangrove Visualization System
**Analysis Date:** $(date)
**Report ID:** $TIMESTAMP

## Project Metrics
- **Location:** $PROJECT_DIR
- **Technology:** Python/Django + Docker
- **Analysis Tools:** Manual FPA + Python Code Analysis

## Code Metrics
\`\`\`
$(cat "$REPORT_DIR/python_analysis_$TIMESTAMP.txt")
\`\`\`

## Functional Point Analysis Results
- **Total Function Points:** 82 FP
- **Lines of Code:** 617
- **LOC per FP:** 7.5
- **Estimated Effort:** 10.25 person-months
- **Complexity:** Medium

## Key Findings
1. **Size:** Medium-scale web application (82 FP)
2. **Architecture:** Well-structured Django application
3. **Technology Stack:** Modern GIS web application
4. **Quality:** Good maintainability and modularity
5. **Scalability:** Docker-based deployment ready

## Recommendations
1. Implement comprehensive unit tests
2. Add API documentation (Swagger/OpenAPI)
3. Enhance error handling and user feedback
4. Add performance monitoring and caching
5. Consider adding batch processing capabilities

## Files Generated
- \`python_analysis_$TIMESTAMP.txt\` - Code metrics
- \`FUNCTIONAL_POINT_ANALYSIS.md\` - Detailed FPA report
- \`PANDUAN_FPA_PHPMETRICS.md\` - FPA methodology guide

---
*Generated by FPA Analysis Runner*
EOF

echo "✓ Summary report created: $REPORT_DIR/summary_$TIMESTAMP.md"
echo ""
echo "=========================================="
echo "Analysis Complete!"
echo "Reports saved in: $REPORT_DIR"
echo "=========================================="
echo ""
echo "Key files:"
echo "- $REPORT_DIR/summary_$TIMESTAMP.md (Summary)"
echo "- $PROJECT_DIR/FUNCTIONAL_POINT_ANALYSIS.md (Detailed FPA)"
echo "- $PROJECT_DIR/PANDUAN_FPA_PHPMETRICS.md (Methodology Guide)"
echo ""
echo "Next steps:"
echo "1. Review the detailed FPA report"
echo "2. Implement recommended improvements"
echo "3. Set up automated analysis in CI/CD pipeline"