# Generated by Django 5.0.7 on 2025-10-09 02:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='rasters/')),
                ('epsg', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('minx', models.FloatField(blank=True, null=True)),
                ('miny', models.FloatField(blank=True, null=True)),
                ('maxx', models.FloatField(blank=True, null=True)),
                ('maxy', models.FloatField(blank=True, null=True)),
                ('reprojected_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MangroveSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(blank=True, max_length=200)),
                ('canopy_cover', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='mangroves_m_name_c86e47_idx'), models.Index(fields=['species'], name='mangroves_m_species_98d441_idx')],
            },
        ),
    ]
