# Generated by Django 5.0.7 on 2025-10-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangroves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterlayer',
            name='tiles_dir',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rasterlayer',
            name='tiles_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rasterlayer',
            name='tiles_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('ok', 'OK'), ('error', 'Error')], default='none', max_length=16),
        ),
    ]
